DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'binflow_app') THEN
    CREATE ROLE binflow_app
      LOGIN
      PASSWORD 'binflow_local_app'
      NOSUPERUSER
      NOCREATEDB
      NOCREATEROLE
      NOINHERIT
      NOBYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE binflow TO binflow_app;
GRANT USAGE ON SCHEMA public TO binflow_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO binflow_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO binflow_app;

ALTER DEFAULT PRIVILEGES FOR ROLE binflow IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO binflow_app;
ALTER DEFAULT PRIVILEGES FOR ROLE binflow IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO binflow_app;
