export {
  EditTextExecutor,
  applyTextFieldPatch,
  buildTextEditGithubDraftFiles,
  buildTextEditKey,
  discoverEditableCopy,
  fallbackTextEditGithubPath,
  resolveTextEditCandidate,
  searchEditableCopy,
  verifyProductionTextVisible,
  type EditTextExecuteInput,
  type TextEditGithubDraftFile,
  type TextEditPatchArtifact,
  type TextEditPreviewResult,
  type TextEditPublishResult,
  type OrbitypeTextPagesPort,
  type TextEditCandidate,
} from './edit-text.js';
